# system
mode: 0
distribute: True
num_parallel_workers: 8
val_while_train: True

# dataset
dataset: "imagenet"
data_dir: "/path/to/imagenet"
shuffle: True
dataset_download: False
batch_size: 128
drop_remainder: True

# augmentation
image_resize: 256
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
interpolation: "bicubic"
auto_augment: "randaug-m9-mstd0.5-inc1"
re_prob: 0.25
crop_pct: 0.9
mixup: 0.8
cutmix: 1.0
aug_repeats: 3

# model
model: "resnest101"
num_classes: 1000
pretrained: False
ckpt_path: ""
keep_checkpoint_max: 30
ckpt_save_dir: "./ckpt"
epoch_size: 360
dataset_sink_mode: True
amp_level: "O2"
drop_rate: 0.2

# loss
loss: "CE"
label_smoothing: 0.1

# lr scheduler
scheduler: "cosine_decay"
min_lr: 0.0
lr: 0.1
warmup_epochs: 15
decay_epochs: 345

# optimizer
opt: "momentum"
momentum: 0.9
weight_decay: 0.00009
loss_scale_type: "auto"
use_nesterov: False
