# system
mode: 0
distribute: True
num_parallel_workers: 8
val_while_train: True

# dataset
dataset: 'imagenet'
data_dir: '/path/to/imagenet'
shuffle: True
dataset_download: False
batch_size: 128
drop_remainder: True

# augmentation
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
vflip: 0.0
interpolation: 'bilinear'
crop_pct: 0.875
color_jitter: 0.4
re_prob: 0.25
re_ratio: [0.3, 3.333]
mixup: 0.2
cutmix: 1.0
cutmix_prob: 1.0
auto_augment: 'randaug-m9-mstd0.5-inc1'


# model
model: 'repmlp_t224'
num_classes: 1000
in_channels: 3
pretrained: False
ckpt_path: ''
keep_checkpoint_max: 10
ckpt_save_dir: './ckpt'
epoch_size: 300
dataset_sink_mode: True
amp_level: 'O2'

# loss
loss: 'ce'
label_smoothing: 0.1

# lr scheduler
scheduler: 'cosine_decay'
lr: 0.005
min_lr: 1e-5
warmup_epochs: 10
decay_epochs: 290
decay_rate: 0.01

# optimizer
opt: 'adamw'
momentum: 0.9
weight_decay: 2e-05
loss_scale: 1024
use_nesterov: False
