# system
mode: 0
distribute: True
val_while_train: True
val_interval: 1
log_interval: 100

# dataset
dataset: 'imagenet'
data_dir: '/path/to/imagenet'
shuffle: True
num_parallel_workers: 8
batch_size: 64

# augmentation
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
vflip: 0.0
interpolation: 'bilinear'
color_jitter: 0.4
re_prob: 0.1

# model
model: 'regnet_x_800mf'
num_classes: 1000
keep_checkpoint_max: 10
ckpt_save_dir: './ckpt'
ckpt_save_interval: 1
ckpt_save_policy: 'latest_k'
epoch_size: 200
dataset_sink_mode: True
amp_level: 'O3'

# loss
loss: 'CE'
label_smoothing: 0.1

# lr scheduler
scheduler: 'cosine_decay'
min_lr: 0.0
lr: 0.1
warmup_epochs: 5
warmup_factor: 0.01
decay_epochs: 195
lr_epoch_stair: True

# optimizer
opt: 'momentum'
momentum: 0.9
weight_decay: 0.0001
loss_scale: 128
use_nesterov: False
